runtime! archlinux.vim

let skip_defaults_vim=1

set number

" Enable completion where available.(ALE)
let g:ale_completion_enabled = 1

syntax enable
set background=dark

set wildmenu

"Use spaces instead of tabs
set expandtab

"Be smart when using tabs ;)
set smarttab

"1 tab = 4 spaces
set shiftwidth=4
set tabstop=4

set ai "Auto indent

set si "Smart indent

" Keep selection after index
vnoremap < <gv
vnoremap > >gv

set lazyredraw "Keeps vim from redrawing the window so often

"Turn most backup options off
set nobackup
set nowb
set noswapfile

" control+n to open nerdTree
map <C-n> :NERDTreeToggle<CR>

" control+p for fzf
map <C-p> :Files<CR>

"vim markdown
"LaTeX math
let g:vim_markdown_math = 1

call plug#begin()
Plug 'w0rp/ale'
Plug 'ervandew/supertab'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'digitaltoad/vim-pug'
Plug 'scrooloose/nerdcommenter'
Plug 'jelera/vim-javascript-syntax'
"Plug 'terryma/vim-multiple-cursors'
call plug#end() 
