#!/usr/bin/env bash

function print {
    amixer="$(amixer sget Master | grep 'Left:')"
    
    volume="$(echo $amixer | awk -F'[][]'  '{ print $2 }')"
    status="$(echo $amixer | awk -F'[][]'  '{ print $4 }')"

    if [[ $status =~ "on" ]] ; then
        out=" $volume"
    elif [[ $status =~ "off" ]] ; then
        out=" ($volume)"
    fi

    echo $out
}

print

pactl subscribe | grep --line-buffered -P "change.*?sink" | while read line
do
    print
done
